version: "3.8"

services:
    laravel.backend:
        image: laravelapp-dev
        build:
            context: ../../
            dockerfile: Dockerfile
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
        env_file:
            - ../../.env
        volumes:
            - ../../:/var/www
        networks:
            - productnetwork
        depends_on:
            - mysql
        restart: unless-stopped

    mysql:
        image: mysql:8.0.42
        env_file:
            - ../../.env.mysql
        ports:
            - "3306:3306"
        volumes:
            - mysqlvol:/var/lib/mysql
        networks:
            - productnetwork
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
            interval: 10s
            timeout: 5s
            retries: 5

    nginx:
        image: nginx:alpine
        ports:
            - "8080:80"
        volumes:
            - ../../:/var/www
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - laravel.backend
        networks:
            - productnetwork
        restart: unless-stopped

networks:
    productnetwork:

volumes:
    mysqlvol:
